---
title: "R Notebook"
output: html_notebook
---

Wczytujemy pakiety

```{r}
library(readxl)
library(ggplot2)
```

Wczytujemy dane

```{r}
rent <- read_excel("../data-raw/rent-poznan.xlsx")
head(rent)
```

Przedstawimy relację miedzy powierzchnią, a ceną nieruchomości

```{r}
ggplot(data = rent, 
       aes(x = flat_area, y = price, color = flat_for_students)) + 
  geom_point(shape = 1) + 
  geom_smooth(method = "lm") +
  #geom_smooth(method = MASS::rlm, color = "red") +
  #facet_wrap(~ flat_for_students) +
  scale_y_log10() +
  scale_x_log10() +
  scale_color_brewer(type = "qual", palette = "Set1")
```


Zapisujemy wykres do obiektu

```{r}
wykres1 <- ggplot(data = rent, 
                  aes(x = flat_area, y = price, color = flat_for_students)) + 
          geom_point(shape = 1) + 
          geom_smooth(method = "lm") +
          #geom_smooth(method = MASS::rlm, color = "red") +
          #facet_wrap(~ flat_for_students) +
          scale_y_log10() +
          scale_x_log10() +
          scale_color_brewer(type = "qual", palette = "Set1")
```

Wykres jest obiektem, który możemy później udostępnić każdemu użytkownikowi R oraz pakietu ggplot2. Wystarczy ten obiekt zapisać np. do pliku z rozszerzeniem .rda/.rds.

```{r}
str(wykres1,1)
wykres1
```

Zapisujemy wykres do pliku z rozszerzeniem png i pdf

```{r}
ggsave(plot = wykres1, filename = "../figures/wykres1.png")
ggsave(plot = wykres1, filename = "../figures/wykres1.png", 
       width=7, height = 5)

ggsave(plot = wykres1, filename = "../figures/wykres1.pdf")
```

