---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(readxl)
library(lubridate)
library(scales)
library(stringi)
```

```{r}
rent <- read_excel("../data-raw/rent-poznan.xlsx")
head(rent)
```

```{r}
ggplot(data = rent, aes(x = flat_area)) +
  geom_histogram() +
  # scale_x_log10() +
  scale_x_continuous(
    trans = "log",
    # trans = scales::log_trans(), 
    breaks = scales::trans_breaks("log", function(x) exp(x)),
    labels = scales::trans_format("log", function(x) x)
    )
```

```{r}
ggplot(data = rent, aes(x = log(flat_area))) +
  geom_histogram()
```

```{r}
scale_x_ln <- function(...) {
  scale_x_continuous(
    ...,
    trans = scales::log_trans(),
    breaks = scales::trans_breaks("log", function(x) exp(x)),
    labels = scales::trans_format("log", function(x) x))
}

ggplot(data = rent, aes(x = flat_area)) +
  geom_histogram() +
  scale_x_ln(name = "log(flat_area)") +
  # scale_y_continuous(labels = scales::comma_format()) +
  scale_y_continuous(
    labels = scales::number_format(accuracy = 1, 
                                   scale = 1/1000,
                                   suffix = " PLN")
    )

```






Praca z datami i jak można je wykorzystać w pakiecie ggplot2

```{r}
daty <- c("11 listopada 2021", "2 stycznia 2019")
```

```{r}
stri_datetime_parse(daty, format = "date_long", locale = "pl_PL")
```


```{r}
daty2 <- c("2021/06/15", "2019-06-15", 
           "2019 06 15", "2019.05.15", "20190615")
```


```{r}
ymd(daty2)
```


```{r}
daty3 <- c("2021/15/06", "15-06-2021", "2021-06-20", "15/6/2021")
```


```{r}
daty3_ok <- parse_date_time(x = daty3, 
                            orders = c("ydm", "ymd", "dmy"))
daty3_ok
```




```{r}
year(daty3_ok)
month(daty3_ok)
day(daty3_ok)
wday(daty3_ok, week_start = 1, label = TRUE, abbr = FALSE)

```

```{r}
floor_date(daty3_ok, unit = "month")
ceiling_date(daty3_ok, unit = "month") 
round_date(daty3_ok, unit = "month")
round_date(daty3_ok, unit = "year")
```


```{r}
rent %>%
  group_by(miesiac = floor_date(as.Date(date_modif), unit = "month"),
           student = flat_for_students) %>%
  summarise(med = median(price),
            med_q1 = quantile(price, 0.25),
            med_q45 = quantile(price, 0.45),
            med_q55 = quantile(price, 0.55),
            med_q3 = quantile(price, 0.75)) %>%
  
  ggplot(data = ., aes(x = miesiac, y = med)) + 
    geom_ribbon(aes(ymin = med_q1, ymax = med_q3), alpha = 0.3) + 
    geom_ribbon(aes(ymin = med_q45, ymax = med_q55), alpha = 0.6) + 
    geom_line() + 
    facet_wrap(~ student)
```





```{r}
rent %>%
  group_by(miesiac = floor_date(as.Date(date_modif), unit = "month"),
           pokoje = ifelse(flat_rooms <= 3, flat_rooms, 4)) %>%
  summarise(med = median(price),
            med_q1 = quantile(price, 0.25),
            med_q3 = quantile(price, 0.75),
            med_q45 = quantile(price, 0.45),
            med_q55 = quantile(price, 0.55),
            n = n()) %>%
  ggplot(data = ., aes(x = miesiac, y = med)) +
    geom_ribbon(aes(ymin = med_q45, ymax = med_q55), alpha = 0.6) + 
    geom_ribbon(aes(ymin = med_q1, ymax = med_q3), alpha = 0.3) + 
    geom_line() +
    facet_wrap(~ pokoje, ncol = 2, scales = "free_y")
```


